repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        exclude: (dist|venv)/
        description: 'Black: The uncompromising Python code formatter'
        entry: black
        # args: ['--check']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        exclude: (dist|venv)/
        description: 'Enforce style consistency'
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        description: 'Sort your imports'
        exclude: (dist|venv)/
        args: ['--profile', 'black']
        # args: ['--check-only']
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        name: interrogate
        exclude: (dist|json|data|data_format)/
        description: 'Checks code base for missing docstrings'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        description: Prevents commit of files > 1 MB
        args: ['--maxkb=1000']

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
